version: '3.9'

services:
  web:
    build: ./django
    command: gunicorn dockerized_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: \
      POSTGRES_USER: \
      POSTGRES_PASSWORD: \

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data:
