image:
  repository: 390825963955.dkr.ecr.eu-west-1.amazonaws.com/lesson-7-ecr
  tag: latest
  # pullPolicy: IfNotPresent
  pullPolicy: Always
  digest: "{{ now | unixEpoch }}"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

env:
  DJANGO_DEBUG: "False"
  # DJANGO_ALLOWED_HOSTS: "*"
  # DJANGO_ALLOWED_HOSTS: "acd47c8fb581a4ae0977739e1654fa85-764943408.eu-west-1.elb.amazonaws.com"
  # ALLOWED_HOSTS: '["acd47c8fb581a4ae0977739e1654fa85-764943408.eu-west-1.elb.amazonaws.com"]'
  # DATABASE_URL: "postgres://django:secretpass@postgres-db-postgresql.default.svc.cluster.local:5432/django_db"
  DB_HOST: "postgres-db-postgresql.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "django_db"
  DB_USER: "django"               
  DB_PASSWORD: "secretpass" 