apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DJANGO_DEBUG: "{{ .Values.env.DJANGO_DEBUG }}"
  DJANGO_ALLOWED_HOSTS: "{{ .Values.env.DJANGO_ALLOWED_HOSTS }}"
  ALLOWED_HOSTS: "{{ .Values.env.DJANGO_ALLOWED_HOSTS }}"
  DATABASE_URL: "{{ .Values.env.DATABASE_URL }}"
  DB_HOST: "{{ .Values.env.DB_HOST }}"
  DB_PORT: "{{ .Values.env.DB_PORT }}"
  DB_NAME: "{{ .Values.env.DB_NAME }}"  
  DB_USER: "{{ .Values.env.DB_USER }}"               
  DB_PASSWORD: "{{ .Values.env.DB_PASSWORD }}" 
  